### ISSUE TITLE
specfem2d nightly build has failed

### ISSUE THREAD

**Issue by buildbot-princeton** [geodynamics/specfem2d#586] opened 2016-06-22 02:00 UTC
See [build 198](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_nightly/builds/198).

**Comment by QuLogic** [comment] 2016-06-22 02:04
Looks like it was caused by a73558b165441c4b9990d5ae8cd30ac1b38bc0f5. cc @danielpeter 

Those conditional imports are broken; they check multiple things in separate `if`, but there are no corresponding `else`s, so the import is done in only a few cases.

**Comment by danielpeter** [comment] 2016-06-22 15:31
should be fixed by PR #587

**Closed** 2016-07-25 22:45 UTC
